Omitting export in backend smoke test

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -331,7 +331,6 @@ jobs:
       - checkout
       - install_awscli
       - install_nodejs
-
       - run:
           name: Backend smoke test.
           command: |
@@ -339,14 +338,15 @@ jobs:
             --query "Reservations[*].Instances[*].[PublicIpAddress]" \
             --filters "Name=tag:Name,Values=backend-${CIRCLE_WORKFLOW_ID:0:7}" \
             --output text)
-
-            export API_URL="http://${BACKEND_PUBLIC_IP}:3030"
-            if curl -s ${API_URL}/api/status | grep "ok"
+            if curl -s http://${BACKEND_PUBLIC_IP}:3030/api/status | grep "ok"
             then
-              return 0
+              echo "Backend Smoke Test Success"
+              exit 0
             else
-              return 1
-            fi 
+              echo "Backend Smoke Test Failed"
+              exit 1
+            fi
+#            export API_URL="http://${BACKEND_PUBLIC_IP}:3030"
 
       - run:
           name: Frontend smoke test.
